# Generated by Django 6.0.4 on 2026-04-17 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(choices=[('produit', 'Produits'), ('charge', 'Charges')], max_length=10)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sous-catégorie de budget',
                'verbose_name_plural': 'Sous-catégories de budget',
                'ordering': ['group', 'ordre', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_bas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('scenario_moyen', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('scenario_haut', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('ligne_budgetaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='config_app.lignebudgetaire')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budget.budgetsubcategory')),
            ],
            options={
                'verbose_name': 'Ligne de budget calculée',
                'verbose_name_plural': 'Lignes de budget calculées',
                'ordering': ['ordre', 'ligne_budgetaire__nom'],
            },
        ),
    ]
