# Generated by Django 6.0.4 on 2026-04-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budgetsubcategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
