# Generated by Django 6.0.4 on 2026-04-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budgetitem_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='formula_moyen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
