# Generated by Django 6.0.4 on 2026-04-16 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_app', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Étude',
                'verbose_name_plural': 'Études',
                'ordering': ['reference'],
            },
        ),
        migrations.CreateModel(
            name='BulletinVersement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('date_operation', models.DateField()),
                ('date_emission', models.DateField(blank=True, null=True)),
                ('reference_virement', models.CharField(blank=True, max_length=100)),
                ('intervenant_nom', models.CharField(max_length=100)),
                ('intervenant_prenom', models.CharField(max_length=100)),
                ('nb_jeh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('retribution_brute_par_jeh', models.DecimalField(decimal_places=2, max_digits=8)),
                ('taux', models.CharField(choices=[('A', 'Taux A'), ('B', 'Taux B'), ('C', 'Taux C'), ('D', 'Taux D')], default='A', max_length=2)),
                ('type_cotisant', models.CharField(choices=[('junior', 'Junior-Entreprise'), ('etudiant', 'Étudiant')], default='etudiant', max_length=20)),
                ('assiette', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cotis_assurance_maladie', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cotis_accident_travail', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cotis_vieillesse_plafonnee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cotis_vieillesse_deplafonnee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cotis_allocations_familiales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cotis_csg_deductible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cotis_csg_non_deductible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cotisations_junior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cotisations_etudiant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_versement', to='operations.operation')),
                ('etude', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins', to='finance.etude')),
            ],
            options={
                'verbose_name': 'Bulletin de versement',
                'verbose_name_plural': 'Bulletins de versement',
                'ordering': ['-date_operation', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='FactureAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('fournisseur', models.CharField(max_length=255)),
                ('libelle', models.CharField(blank=True, max_length=255)),
                ('lien_drive', models.URLField(blank=True, max_length=500)),
                ('date_operation', models.DateField()),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('categorisation', models.CharField(choices=[('service', 'Service'), ('bien', 'Bien'), ('immobilisation', 'Immobilisation')], default='service', max_length=20)),
                ('immobilisation', models.BooleanField(default=False, help_text='Auto si Bien > 500€, non modifiable manuellement')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('taux_compose', models.BooleanField(default=False)),
                ('pays_tva', models.CharField(choices=[('FR', 'France'), ('intracom', 'Intracom UE'), ('extracom', 'Extra UE')], default='FR', max_length=20)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ligne_budgetaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config_app.lignebudgetaire')),
                ('operation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture_achat', to='operations.operation')),
                ('type_achat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='config_app.typeachat')),
            ],
            options={
                'verbose_name': "Facture d'achat",
                'verbose_name_plural': "Factures d'achat",
                'ordering': ['-date_operation', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='FactureVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('libelle', models.CharField(blank=True, max_length=255)),
                ('lien_drive', models.URLField(blank=True, max_length=500)),
                ('date_operation', models.DateField()),
                ('date_envoi', models.DateField(blank=True, null=True)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('taux_mixte', models.BooleanField(default=False)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pays_tva', models.CharField(choices=[('FR', 'France'), ('intracom', 'Intracom UE'), ('extracom', 'Extra UE')], default='FR', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etude', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_vente', to='finance.etude')),
                ('ligne_budgetaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config_app.lignebudgetaire')),
                ('operation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture_vente', to='operations.operation')),
                ('type_facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='config_app.typefacturevente')),
            ],
            options={
                'verbose_name': 'Facture de vente',
                'verbose_name_plural': 'Factures de vente',
                'ordering': ['-date_operation', '-numero'],
            },
        ),
    ]
