# Generated by Django 6.0.4 on 2026-04-17 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinversement',
            name='ligne_budgetaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins', to='config_app.lignebudgetaire'),
        ),
    ]
