# Generated by Django 6.0.4 on 2026-04-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_bulletinversement_ligne_budgetaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletinversement',
            name='cotis_accident_travail',
        ),
        migrations.RemoveField(
            model_name='bulletinversement',
            name='cotis_allocations_familiales',
        ),
        migrations.RemoveField(
            model_name='bulletinversement',
            name='cotis_assurance_maladie',
        ),
        migrations.RemoveField(
            model_name='bulletinversement',
            name='cotis_csg_deductible',
        ),
        migrations.RemoveField(
            model_name='bulletinversement',
            name='cotis_csg_non_deductible',
        ),
        migrations.RemoveField(
            model_name='bulletinversement',
            name='cotis_vieillesse_deplafonnee',
        ),
        migrations.RemoveField(
            model_name='bulletinversement',
            name='cotis_vieillesse_plafonnee',
        ),
        migrations.RemoveField(
            model_name='bulletinversement',
            name='taux',
        ),
        migrations.RemoveField(
            model_name='bulletinversement',
            name='total_cotisations_etudiant',
        ),
        migrations.RemoveField(
            model_name='bulletinversement',
            name='total_cotisations_junior',
        ),
        migrations.RemoveField(
            model_name='bulletinversement',
            name='type_cotisant',
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='e_accident_travail',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='e_allocations_familiales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='e_assurance_maladie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='e_csg_deductible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='e_csg_non_deductible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='e_vieillesse_deplafonnee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='e_vieillesse_plafonnee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='j_accident_travail',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='j_allocations_familiales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='j_assurance_maladie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='j_csg_deductible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='j_csg_non_deductible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='j_vieillesse_deplafonnee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='j_vieillesse_plafonnee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='nom_mission',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='num_secu',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='ref_avrm',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='ref_rm',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='total_etudiant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='total_global',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='total_junior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulletinversement',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
