# Generated by Django 6.0.4 on 2026-04-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_bulletinversement_cotis_accident_travail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinversement',
            name='lien_drive',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
