# Generated by Django 6.0.4 on 2026-04-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_bulletinversement_lien_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturevente',
            name='tiers',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
