# Generated by Django 6.0.4 on 2026-04-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_facturevente_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinversement',
            name='date_envoi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
