# Generated by Django 6.0.4 on 2026-04-25 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_bulletinversement_date_envoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureachat',
            name='rib_beneficiaire',
            field=models.CharField(blank=True, help_text='RIB du bénéficiaire pour remboursement', max_length=34),
        ),
        migrations.CreateModel(
            name='DemandeNDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nom_beneficiaire', models.CharField(max_length=255)),
                ('rib_beneficiaire', models.CharField(max_length=34)),
                ('justificatif', models.FileField(upload_to='preuve_NDF/')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Validée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('commentaire_tresorier', models.TextField(blank=True)),
                ('facture_achat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_ndf', to='finance.factureachat')),
            ],
            options={
                'verbose_name': 'Demande de Note de Frais',
                'verbose_name_plural': 'Demandes de Notes de Frais',
            },
        ),
        migrations.CreateModel(
            name='LigneNDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('est_ik', models.BooleanField(default=False)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='finance.demandendf')),
            ],
        ),
    ]
