# Generated by Django 6.0.4 on 2026-04-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_factureachat_rib_beneficiaire_demandendf_lignendf'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandendf',
            name='prenom_beneficiaire',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demandendf',
            name='nom_beneficiaire',
            field=models.CharField(max_length=100),
        ),
    ]
