# Generated by Django 6.0.4 on 2026-04-25 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_demandendf_prenom_beneficiaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandendf',
            name='justificatif',
        ),
        migrations.AddField(
            model_name='demandendf',
            name='libelle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='demandendf',
            name='type_frais',
            field=models.CharField(choices=[('ik', 'Frais Kilométriques'), ('achat', 'Achats au nom de Ouest INSA')], default='achat', max_length=20),
        ),
        migrations.CreateModel(
            name='JustificatifNDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='preuve_NDF/')),
                ('nom_original', models.CharField(blank=True, max_length=255)),
                ('type_pièce', models.CharField(blank=True, max_length=50)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificatifs', to='finance.demandendf')),
            ],
        ),
    ]
