# Generated by Django 6.0.4 on 2026-04-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_remove_demandendf_justificatif_demandendf_libelle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandendf',
            name='commentaire_demandeur',
            field=models.TextField(blank=True, verbose_name='Commentaire du demandeur'),
        ),
    ]
