# Generated by Django 6.0.4 on 2026-04-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_demandendf_commentaire_demandeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandendf',
            name='statut',
            field=models.CharField(choices=[('pending', 'En attente'), ('waiting_payment', 'En attente de paiement'), ('approved', 'Validée'), ('completed', 'Traitée et Payée'), ('rejected', 'Rejetée')], default='pending', max_length=20),
        ),
    ]
