# Generated by Django 6.0.4 on 2026-04-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_demandendf_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificatifndf',
            name='label_personnalise',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom personnalisé'),
        ),
        migrations.AlterField(
            model_name='demandendf',
            name='statut',
            field=models.CharField(choices=[('pending', 'En attente'), ('needs_info', 'À compléter'), ('waiting_payment', 'En attente de paiement'), ('approved', 'Validée'), ('completed', 'Traitée et Payée'), ('rejected', 'Rejetée')], default='pending', max_length=20),
        ),
    ]
