# Generated by Django 6.0.4 on 2026-04-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationTVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(help_text='Format AAAAMM (ex: 202406)', max_length=6, unique=True)),
                ('switch_calcul', models.CharField(choices=[('operation', "Date d'opération bancaire"), ('facture', 'Date de facture')], default='operation', help_text="Base de calcul : date d'opération ou date de facture", max_length=20)),
                ('finalisee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ligne_A1', models.DecimalField(decimal_places=2, default=0, help_text='A1 — Ventes et prestations de services HT', max_digits=14)),
                ('ligne_A2', models.DecimalField(decimal_places=2, default=0, help_text='A2 — Autres opérations imposables', max_digits=14)),
                ('ligne_A3', models.DecimalField(decimal_places=2, default=0, help_text='A3 — Importations', max_digits=14)),
                ('ligne_A4', models.DecimalField(decimal_places=2, default=0, help_text='A4 — Sorties de régime', max_digits=14)),
                ('ligne_A5', models.DecimalField(decimal_places=2, default=0, help_text='A5 — Autres opérations', max_digits=14)),
                ('ligne_B1', models.DecimalField(decimal_places=2, default=0, help_text='B1 — Livraisons intracommunautaires', max_digits=14)),
                ('ligne_B2', models.DecimalField(decimal_places=2, default=0, help_text='B2 — Acquisitions intracommunautaires HT', max_digits=14)),
                ('ligne_B3', models.DecimalField(decimal_places=2, default=0, help_text='B3 — Autres opérations non imposables', max_digits=14)),
                ('ligne_B4', models.DecimalField(decimal_places=2, default=0, help_text='B4 — Autres catégories', max_digits=14)),
                ('ligne_B5', models.DecimalField(decimal_places=2, default=0, help_text='B5 — Autres catégories', max_digits=14)),
                ('ligne_E1', models.DecimalField(decimal_places=2, default=0, help_text='E1 — Exportations hors UE', max_digits=14)),
                ('ligne_E2', models.DecimalField(decimal_places=2, default=0, help_text='E2 — Autres opérations non imposables (cotisations)', max_digits=14)),
                ('ligne_08_base', models.DecimalField(decimal_places=2, default=0, help_text='08 — Base imposable taux normal 20%', max_digits=14)),
                ('ligne_08_taxe', models.DecimalField(decimal_places=2, default=0, help_text='08 — TVA due taux normal 20%', max_digits=14)),
                ('ligne_09_base', models.DecimalField(decimal_places=2, default=0, help_text='09 — Base imposable taux réduit 10%', max_digits=14)),
                ('ligne_09_taxe', models.DecimalField(decimal_places=2, default=0, help_text='09 — TVA due taux réduit 10%', max_digits=14)),
                ('ligne_09b_base', models.DecimalField(decimal_places=2, default=0, help_text='09b — Base imposable taux réduit 5,5%', max_digits=14)),
                ('ligne_09b_taxe', models.DecimalField(decimal_places=2, default=0, help_text='09b — TVA due taux réduit 5,5%', max_digits=14)),
                ('ligne_16', models.DecimalField(decimal_places=2, default=0, help_text='16 — Total TVA brute due (08+09+09b)', max_digits=14)),
                ('ligne_17', models.DecimalField(decimal_places=2, default=0, help_text='17 — Dont TVA sur acquisitions intracommunautaires', max_digits=14)),
                ('ligne_20', models.DecimalField(decimal_places=2, default=0, help_text='20 — Autres biens et services (TVA factures achats)', max_digits=14)),
                ('ligne_21', models.DecimalField(decimal_places=2, default=0, help_text='21 — Autre TVA à déduire', max_digits=14)),
                ('ligne_22', models.DecimalField(decimal_places=2, default=0, help_text='22 — Report du crédit (ligne 27 du mois précédent)', max_digits=14)),
                ('ligne_22_modifiee_manuellement', models.BooleanField(default=False, help_text='Indique si la ligne 22 a été saisie manuellement')),
                ('ligne_23', models.DecimalField(decimal_places=2, default=0, help_text='23 — Total TVA déductible (19+20+21+22)', max_digits=14)),
                ('ligne_25', models.DecimalField(decimal_places=2, default=0, help_text='25 — Crédit de TVA (23-16)', max_digits=14)),
                ('ligne_27', models.DecimalField(decimal_places=2, default=0, help_text='27 — Crédit à reporter', max_digits=14)),
                ('ligne_28', models.DecimalField(decimal_places=2, default=0, help_text='28 — TVA nette due (16-23)', max_digits=14)),
                ('ligne_32', models.DecimalField(decimal_places=2, default=0, help_text='32 — Total à payer', max_digits=14)),
            ],
            options={
                'verbose_name': 'Déclaration TVA',
                'verbose_name_plural': 'Déclarations TVA',
                'ordering': ['-periode'],
            },
        ),
    ]
