# Generated by Django 6.0.4 on 2026-04-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declarationtva',
            name='ligne_08_base',
        ),
        migrations.RemoveField(
            model_name='declarationtva',
            name='ligne_08_taxe',
        ),
        migrations.RemoveField(
            model_name='declarationtva',
            name='ligne_09_base',
        ),
        migrations.RemoveField(
            model_name='declarationtva',
            name='ligne_09_taxe',
        ),
        migrations.RemoveField(
            model_name='declarationtva',
            name='ligne_09b_base',
        ),
        migrations.RemoveField(
            model_name='declarationtva',
            name='ligne_09b_taxe',
        ),
        migrations.RemoveField(
            model_name='declarationtva',
            name='ligne_22_modifiee_manuellement',
        ),
        migrations.RemoveField(
            model_name='declarationtva',
            name='ligne_A4',
        ),
        migrations.RemoveField(
            model_name='declarationtva',
            name='ligne_A5',
        ),
        migrations.RemoveField(
            model_name='declarationtva',
            name='ligne_B1',
        ),
        migrations.RemoveField(
            model_name='declarationtva',
            name='ligne_B3',
        ),
        migrations.RemoveField(
            model_name='declarationtva',
            name='ligne_B4',
        ),
        migrations.RemoveField(
            model_name='declarationtva',
            name='ligne_B5',
        ),
        migrations.RemoveField(
            model_name='declarationtva',
            name='ligne_E1',
        ),
        migrations.AddField(
            model_name='declarationtva',
            name='date_validation',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle la déclaration a été figée', null=True),
        ),
        migrations.AddField(
            model_name='declarationtva',
            name='lien_accuse_reception',
            field=models.URLField(blank=True, help_text="Lien vers l'accusé de réception", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='declarationtva',
            name='lien_declaration',
            field=models.URLField(blank=True, help_text='Lien vers la déclaration de TVA', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='declarationtva',
            name='lien_ordre_paiement',
            field=models.URLField(blank=True, help_text="Lien vers l'ordre de paiement", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='ligne_16',
            field=models.DecimalField(decimal_places=2, default=0, help_text='16 — Total TVA brute due', max_digits=14),
        ),
    ]
