# Generated by Django 6.0.4 on 2026-04-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_remove_declarationtva_ligne_08_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declarationtva',
            name='ligne_08_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='08 — Base imposable taux normal 20%', max_digits=14),
        ),
        migrations.AddField(
            model_name='declarationtva',
            name='ligne_08_taxe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='08 — TVA due taux normal 20%', max_digits=14),
        ),
    ]
