# Generated by Django 6.0.4 on 2026-04-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_declarationtva_ligne_08_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declarationtva',
            name='ligne_08_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base imposable taux normal 20%', max_digits=14),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='ligne_08_taxe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='TVA due taux normal 20%', max_digits=14),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='ligne_16',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total TVA brute due', max_digits=14),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='ligne_17',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dont TVA sur acquisitions intracommunautaires', max_digits=14),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='ligne_20',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Autres biens et services (TVA factures achats)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='ligne_21',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Autre TVA à déduire', max_digits=14),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='ligne_22',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Report du crédit (ligne 27 du mois précédent)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='ligne_23',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total TVA déductible (19+20+21+22)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='ligne_25',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Crédit de TVA (23-16)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='ligne_27',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Crédit à reporter', max_digits=14),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='ligne_28',
            field=models.DecimalField(decimal_places=2, default=0, help_text='TVA nette due (16-23)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='ligne_32',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total à payer', max_digits=14),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='ligne_B2',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Acquisitions intracommunautaires HT', max_digits=14),
        ),
        migrations.AlterField(
            model_name='declarationtva',
            name='ligne_E2',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Autres opérations non imposables (cotisations)', max_digits=14),
        ),
    ]
