# Generated by Django 6.0.4 on 2026-04-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_alter_declarationtva_ligne_08_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationURSSAF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(help_text='Format AAAAMM (ex: 202406)', max_length=6, unique=True)),
                ('lien_preuve', models.URLField(blank=True, help_text='Lien vers la preuve de déclaration', max_length=500, null=True)),
                ('date_declaration', models.DateTimeField(blank=True, null=True)),
                ('finalisee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Déclaration URSSAF',
                'verbose_name_plural': 'Déclarations URSSAF',
                'ordering': ['-periode'],
            },
        ),
    ]
