# Generated by Django 6.0.4 on 2026-04-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LigneBudgetaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ligne budgétaire',
                'verbose_name_plural': 'Lignes budgétaires',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ParametreCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cotisant', models.CharField(choices=[('junior', 'Junior-Entreprise'), ('etudiant', 'Étudiant')], max_length=20, unique=True)),
                ('base_urssaf', models.DecimalField(decimal_places=2, default=48.08, help_text='Base Urssaf par JEH (€)', max_digits=8)),
                ('assurance_maladie', models.DecimalField(decimal_places=2, default=0, help_text='Taux assurance maladie (%)', max_digits=5)),
                ('accident_travail', models.DecimalField(decimal_places=2, default=0, help_text='Taux accident du travail (%)', max_digits=5)),
                ('vieillesse_plafonnee', models.DecimalField(decimal_places=2, default=0, help_text='Taux vieillesse plafonnée (%)', max_digits=5)),
                ('vieillesse_deplafonnee', models.DecimalField(decimal_places=2, default=0, help_text='Taux vieillesse déplafonnée (%)', max_digits=5)),
                ('allocations_familiales', models.DecimalField(decimal_places=2, default=0, help_text='Taux allocations familiales (%)', max_digits=5)),
                ('csg_deductible', models.DecimalField(decimal_places=2, default=0, help_text='Taux CSG déductible (%)', max_digits=5)),
                ('csg_non_deductible', models.DecimalField(decimal_places=2, default=0, help_text='Taux CSG non déductible (%)', max_digits=5)),
            ],
            options={
                'verbose_name': 'Paramètre cotisation',
                'verbose_name_plural': 'Paramètres cotisations',
            },
        ),
        migrations.CreateModel(
            name='ParametreTVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux', models.DecimalField(decimal_places=2, max_digits=5, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('commentaire', models.TextField(blank=True, help_text="Cas d'application affichés à l'utilisateur")),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Paramètre TVA',
                'verbose_name_plural': 'Paramètres TVA',
                'ordering': ['ordre', 'taux'],
            },
        ),
        migrations.CreateModel(
            name='TypeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('suffixe', models.CharField(choices=[('F', 'Fournisseur'), ('NF', 'Note de frais')], max_length=5)),
                ('active', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Type d'achat",
                'verbose_name_plural': "Types d'achat",
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeFactureVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('suffixe', models.CharField(choices=[('A', 'Acompte'), ('S', 'Solde'), ('C', 'Cotisation'), ('SU', 'Subvention'), ('AV', 'Avoir'), ('R', 'Refacturation')], max_length=5)),
                ('taux_tva_defaut', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('est_cotisation', models.BooleanField(default=False)),
                ('est_subvention', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Type de facture de vente',
                'verbose_name_plural': 'Types de factures de vente',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
