# Generated by Django 6.0.4 on 2026-04-21 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0001_initial'),
        ('finance', '0003_remove_bulletinversement_cotis_accident_travail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutofillRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom usuel de la règle (ex: Frais bancaires)', max_length=100)),
                ('mots_cles', models.CharField(help_text='Mots clés séparés par des virgules', max_length=500)),
                ('condition_type', models.CharField(choices=[('OR', 'Au moins un mot clé (OU)'), ('AND', 'Tous les mots clés (ET)')], default='OR', max_length=3)),
                ('type_operation', models.CharField(choices=[('all', 'Toutes les opérations'), ('credit', 'Ventes / Crédits'), ('debit', 'Achats / Débits')], default='all', max_length=10)),
                ('fournisseur', models.CharField(blank=True, max_length=255, null=True)),
                ('libelle_defaut', models.CharField(blank=True, max_length=255, null=True)),
                ('taux_tva', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pays_tva', models.CharField(blank=True, choices=[('FR', 'France'), ('intracom', 'Intracom UE'), ('extracom', 'Extra UE')], max_length=20, null=True)),
                ('categorisation_achat', models.CharField(blank=True, choices=[('service', 'Service'), ('bien', 'Bien'), ('immobilisation', 'Immobilisation')], max_length=20, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('etude', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.etude')),
                ('ligne_budgetaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config_app.lignebudgetaire')),
            ],
            options={
                'verbose_name': "Règle d'autocomplétion",
                'verbose_name_plural': "Règles d'autocomplétion",
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
