# Generated by Django 6.0.4 on 2026-04-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0002_autofillrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreNDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Indemnité Kilométrique', max_length=100, unique=True)),
                ('montant_ik', models.DecimalField(decimal_places=4, default=0.0, help_text='Montant au km (€)', max_digits=10)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Paramètre NDF',
                'verbose_name_plural': 'Paramètres NDF',
            },
        ),
    ]
