# Generated by Django 6.0.4 on 2026-04-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0003_parametrendf'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president_prenom', models.CharField(default='Prénom', max_length=100)),
                ('president_nom', models.CharField(default='NOM', max_length=100)),
                ('tresorier_prenom', models.CharField(default='Prénom', max_length=100)),
                ('tresorier_nom', models.CharField(default='NOM', max_length=100)),
            ],
            options={
                'verbose_name': 'Configuration Signatures',
                'verbose_name_plural': 'Configuration Signatures',
            },
        ),
    ]
