# Generated by Django 6.0.4 on 2026-04-27 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0004_signatureconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False, help_text='Poste attribué aux emails non répertoriés')),
                ('can_access_ventes', models.BooleanField(default=False)),
                ('can_access_achats', models.BooleanField(default=False)),
                ('can_access_operations', models.BooleanField(default=False)),
                ('can_access_ndf_admin', models.BooleanField(default=False)),
                ('can_access_etudes', models.BooleanField(default=False)),
                ('can_access_settings', models.BooleanField(default=False)),
                ('dashboard_show_kpi_global', models.BooleanField(default=False, help_text='CA, Dépenses, BV, Ops en attente')),
                ('dashboard_show_kpi_ndf_admin', models.BooleanField(default=False, help_text='NDF à valider, à payer, etc.')),
                ('dashboard_show_personal_ndf', models.BooleanField(default=True, help_text="Bloc 'Mes Notes de Frais' personnel")),
                ('dashboard_show_tva_urssaf', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Poste et Permissions',
                'verbose_name_plural': 'Postes et Permissions',
            },
        ),
        migrations.CreateModel(
            name='UserPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='config_app.postepermission')),
            ],
            options={
                'verbose_name': 'Accès Utilisateur',
                'verbose_name_plural': 'Accès Utilisateurs',
            },
        ),
    ]
