# Generated by Django 6.0.4 on 2026-04-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0005_postepermission_userposte'),
    ]

    operations = [
        migrations.AddField(
            model_name='postepermission',
            name='can_access_budget',
            field=models.BooleanField(default=False),
        ),
    ]
