# Generated by Django 6.0.4 on 2026-04-16 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('nb_rows', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Import CSV',
                'verbose_name_plural': 'Imports CSV',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('info_complementaire', models.TextField(blank=True)),
                ('type_operation', models.CharField(choices=[('credit', 'Crédit'), ('debit', 'Débit')], max_length=10)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_operation', models.DateField()),
                ('date_valeur', models.DateField(blank=True, null=True)),
                ('pointage', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('processed', 'Traitée'), ('ignored', 'Ignorée')], default='pending', max_length=20)),
                ('commentaire_ignoree', models.TextField(blank=True, help_text='Commentaire pour virement interne ignoré')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='operations.importbatch')),
            ],
            options={
                'verbose_name': 'Opération',
                'verbose_name_plural': 'Opérations',
                'ordering': ['-date_operation', '-id'],
            },
        ),
    ]
